using Newtonsoft.Json;
using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Stores;
using Nop.Core.Http;
using Nop.Services.Cms;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Plugins;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;

namespace Nop.Plugin.Widgets.TrackerScript
{
    public class TrackerPlugin : BasePlugin, IWidgetPlugin
    {
        private readonly IWebHelper _webHelper;
        private readonly ISettingService _settingService;
        private readonly IWorkContext _workContext;
        private readonly IStoreContext _storeContext;
        private readonly ILocalizationService _localizationService;
        private readonly IHttpClientFactory _httpClientFactory;
        public const string default_TrackingScript = "";

        public const string default_ConversionScript = "";
        public const string default_RemarketingScript = "";

		public bool HideInWidgetList => false;

		public TrackerPlugin(IWebHelper webHelper, ISettingService settingService, IHttpClientFactory httpClientFactory, IWorkContext workContext, IStoreContext storeContext,  ILocalizationService localizationService)
        {
            _webHelper = webHelper;
            _settingService = settingService;
            _workContext = workContext;
            _storeContext = storeContext;
            _localizationService = localizationService;
            _httpClientFactory = httpClientFactory;
        }
      
        public string GetWidgetViewComponentName(string widgetZone)
        {
            return "WidgetsTracker";
        }
        public IList<string> GetWidgetZones()
        {
            return new List<string> { "head_html_tag", "body_end_html_tag_before" };
        }

        public override string GetConfigurationPageUrl()
        {
            return _webHelper.GetStoreLocation() + "Admin/WidgetsTracker/Configure";
        }
        public override void Install()
        {
            var settings = new TrackerSettings
            {
                TrackingScript = default_TrackingScript,
                ConversionScript = default_ConversionScript,
                RemarketingScript = default_RemarketingScript,
                ValidKey = false,
            };
            _settingService.SaveSetting(settings);
           
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.ActivationKey", "Activation Key");
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.ActivationKey.Hint", "Paste the Activation Key Send Via Mail while purchase.");

            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.LoadDefaultTrackingScript", "Reload default tracking script");
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.TrackingScript", "Tracking Script");
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.TrackingScript.Hint", "Paste the tracking code generated by Google Analytics here.");

            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.LoadDefaultConversionScript", "Reload default conversion script");
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.ConversionScript", "Conversion script");
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.ConversionScript.Hint", "Paste the conversion tracking code generated by Google adwords here, and Replace {PRODID},{PAGETYPE},{VALUE},{ORDER_ID},{CUSTOMER_EMAIL},{COUNTRY_CODE},{YYYY-MM-DD},{GTIN},{ORDERTOTAL},{CURRENCY}.");

            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.LoadDefaultRemarketingScript", "Reload default Remarketing script");
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.RemarketingScript", "Remarketing script");
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.RemarketingScript.Hint", "Paste the remarketing script here, and Replace {CATEGORYNAME},{PRODID},{PAGETYPE},{VALUE}.");

            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.ValidKey", "ValidKey");
            _localizationService.AddOrUpdatePluginLocaleResource("Plugins.Widgets.TrackerScript.ValidKey.Hint", "ValidKey.");
            Store sto = _storeContext.CurrentStore;
            string companyAddress = sto.CompanyAddress;
            string storeName = sto.Name;
            string companyPhoneNumber = sto.CompanyPhoneNumber;
            string companyName = sto.CompanyName;
            string hosts = sto.Hosts;
            Customer CurrentUser = _workContext.CurrentCustomer;
            string email = CurrentUser.Email;
            string customerName = CurrentUser.Username;
            var json = new
            {
                host = hosts,
                customerName = customerName,
                customerEmail = email,
                storeName = storeName,
                companyName = companyName,
                companyAddress = companyAddress,
                companyPhone = companyPhoneNumber,
                action = "Installed",
                pluginName = "Tracker Script Plugin",
                version = "4.3"
            };
            RestPost(json);
            base.Install();
        }

        public override void Uninstall()
        {
            Store sto = _storeContext.CurrentStore;
            string companyAddress = sto.CompanyAddress;
            string storeName = sto.Name;
            string companyPhoneNumber = sto.CompanyPhoneNumber;
            string companyName = sto.CompanyName;
            string hosts = sto.Hosts;
            Customer CurrentUser = _workContext.CurrentCustomer;
            string email = CurrentUser.Email;
            string customerName = CurrentUser.Username;
            var json = new
            {
                host = hosts,
                customerName = customerName,
                customerEmail = email,
                storeName = storeName,
                companyName = companyName,
                companyAddress = companyAddress,
                companyPhone = companyPhoneNumber,
                action = "UnInstalled",
                pluginName = "Tracker Script Plugin",
                version = "4.3"
            };
            RestPost(json);

            _settingService.DeleteSetting<TrackerSettings>();

            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.ActivationKey");
            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.ActivationKey.Hint");

            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.LoadDefaultTrackingScript");
            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.TrackingScript");
            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.TrackingScript.Hint");

            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.LoadDefaultConversionScript");
            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.ConversionScript");
            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.ConversionScript.Hint");

            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.LoadDefaultRemarketingScript");
            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.RemarketingScript");
            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.RemarketingScript.Hint");

            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.ValidKey");
            _localizationService.DeletePluginLocaleResource("Plugins.Widgets.TrackerScript.ValidKey.Hint");
            base.Uninstall();
        }

        private void RestPost(object body)
        {
            try
            {
                HttpContent httpContent = new StringContent(JsonConvert.SerializeObject(body), Encoding.UTF8, "application/json");
                var httpClient = _httpClientFactory.CreateClient(NopHttpDefaults.DefaultHttpClient);
                var response = httpClient.PostAsync("https://signupapi.aroopatech.com/api/info", httpContent).Result;
                if (!response.IsSuccessStatusCode)
                {
                    // _logger.Error($"Tracker Script Plugin POST Info failed. status code: {response.StatusCode} message: {response.Content.ReadAsStringAsync().Result}");
                }
            }
            catch (Exception)
            {
              //  _logger.Error("Tracker Script Plugin POST Info.", ex);
            }
        }
    }
}
